version: "3.8"
services:
  app:
    image: jongminhong844/gospace:latest
    container_name: springboot-app
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/school.csv:/app/school.csv
    environment:
      TZ: Asia/Seoul
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_REGION: ${S3_REGION}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      FILE_PATH: ${FILE_PATH}
